/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.util.List; // ✅ use Java's List instead of org.example.list

import static com.taskmanager.core.util.StringUtils.join;
import static com.taskmanager.core.util.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        // Use List<String> instead of LinkedList
        List<String> tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
